db:
  connection : "{ connectionString: 'http://mongodb.com from config server', userName:'gohul', password: 'pass'}"
  host : 123.41.12.12
  port : 1200

app:
  name : My App
  description : welcome to configrRepo

my:
  message: this message is coming from cloudrepo