db:
  connection : "{ connectionString: 'http://mongodb.com from specific file in config server repo', userName:'gohul', password: 'pass'}"
  host : 123.41.12.12
  port : 1200

my:
  message: New updated message is coming from specic file in config-repo


